name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install requirments
      run: pip install -r requirements.txt
    - name: Setup gdrive
      uses: AnimMouse/setup-gdrive@v3
      with:
        service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
    - name: Download from google drive
      run: gdrive download 1xinJL5NwClwEFZvkMoC7LUqJSjf81pnu --service-account client_secrets.json --recursive
    - name: Run python program
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        python SetlistGenerator.py -c ${{ secrets.SPOTIFYCLIENTID }} -s ${{ secrets.SPOTIFYSECRET }} -p https://open.spotify.com/playlist/5uBncQl6gmVXVDS057nUHZ?si=5320e8a974d64426 -r Repertoire/ -o Out
